<a href="https://colab.research.google.com/github/venkatasandeeppothala983-ux/Python/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
test_array = np.array([[1.5, 2.5, 3.5]])
print(test_array)
print(test_array.shape)
print(test_array.ndim)
print(test_array.dtype)

[[1.5 2.5 3.5]]
(1, 3)
2
float64


In [ ]:
hero_matrix = np.array([[1,2],[3,4],[5,6]])
print(hero_matrix[2,1])
print(hero_matrix[:,1])

6
[2 4 6]


In [ ]:
import numpy as np
lst=[2,5,9]
fav=np.array(lst)
print(fav)
print(fav.ndim)
print(fav.shape)
print(fav[1])

[2 5 9]
1
(3,)
5


In [ ]:
challenge_array = np.array([100, 200, 300, 400, 500])
slic=challenge_array[1:4]
print(slic)

[200 300 400]


In [ ]:
import numpy as np

# A 2D list: 2 rows, 3 columns
matrix_list = [[10, 20, 30], [40, 50, 60]]
matrix = np.array(matrix_list)

print(matrix)
# Output:
# [[10 20 30]
#  [40 50 60]]
print(matrix[1,1])
print(matrix[0,2])

[[10 20 30]
 [40 50 60]]
50
30
(2, 3)


In [ ]:
import numpy as np
arr2d=np.zeros((3,2))
arr1d=np.ones(4)
print(arr1d)
print(arr2d)

[1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
mat=np.full((2,2),5)
mat1=np.eye(2)
matr=mat+mat1
print(mat)
print(mat1)
print(matr)

[[5 5]
 [5 5]]
[[1. 0.]
 [0. 1.]]
[[6. 5.]
 [5. 6.]]


In [ ]:
import numpy as np
odd=np.arange(1,10)
nums=np.linspace(0,1,4)
print(odd)
print(nums)

[1 2 3 4 5 6 7 8 9]
[0.         0.33333333 0.66666667 1.        ]


In [ ]:
rani=np.random.randint(10,50,size=(3,3))
print(rani)

[[26 45 20]
 [14 32 38]
 [21 36 39]]


In [ ]:
import numpy as np
package_ids=np.arange(100,119,2)
print(package_ids)
print(package_ids.shape)
print(package_ids.dtype)
weight_matrix=np.random.randint(5,51,size=(3,3))
print(weight_matrix)
print(weight_matrix[:,1])
print(weight_matrix[:2,-2:])
system_clearance=np.eye(4,4)
print(system_clearance)
error_override=np.full(5,99.9)
print(error_override)

[100 102 104 106 108 110 112 114 116 118]
(10,)
int64
[[33 42 27]
 [39 35 49]
 [ 6 22 48]]
[42 35 22]
[[42 27]
 [35 49]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[99.9 99.9 99.9 99.9 99.9]


In [ ]:
###The Metro Smart-Grid Simulation
import numpy as np
power_data = [[120, 150, 90],
              [80,  200, 110],
              [140, 95,  160]]
power_grid=np.array(power_data)
print(power_grid)
print(power_grid.shape)
print(power_grid.ndim)
print(power_grid.dtype)
print(power_grid[1,1])
eastern=power_grid[:,2]
print(eastern)
grid_core=np.eye(4)
print(grid_core)
time_intervals=np.linspace(0,24,5)
print(time_intervals)
passenger_density=np.random.randint(50,501,size=(2,3))
print(passenger_density)

[[120 150  90]
 [ 80 200 110]
 [140  95 160]]
(3, 3)
2
int64
200
[ 90 110 160]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0.  6. 12. 18. 24.]
[[388 455  95]
 [342 247 106]]
[ 80 200 110]
[140  95 160]


In [ ]:
import numpy as np
sensor_data = [[98, 101, 95],
               [102, 97, 100]]
launch_pad_sensors=np.array(sensor_data)
print(launch_pad_sensors)
print(launch_pad_sensors.shape)
print(launch_pad_sensors.ndim)
print(launch_pad_sensors.dtype)
print(launch_pad_sensors[:,1])
print(np.full(6,5.0))
countdown_timers=np.arange(10,0,-1)
print(countdown_timers)
noise_signals=np.random.rand(3,3)
print(noise_signals)
print(np.zeros((2,4)))
print(np.ones(5))
print(np.linspace(0,16,4))

[[ 98 101  95]
 [102  97 100]]
(2, 3)
2
int64
[101  97]
[5. 5. 5. 5. 5. 5.]
[10  9  8  7  6  5  4  3  2  1]
[[0.44381212 0.89695655 0.94802351]
 [0.77605829 0.19817797 0.48128377]
 [0.93989396 0.72529848 0.27556272]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[ 0.          5.33333333 10.66666667 16.        ]


In [ ]:
arr1d=np.arange(1,13)
print(arr1d)
arr=arr1d.reshape(3,4)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
v=np.vstack((a,b))
h=np.hstack((a,b))
print(v)
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
matrix_to_split = np.array([[1, 2, 5, 6],
                            [3, 4, 7, 8]])
left,right=np.hsplit(matrix_to_split,2)
print(left)
print(right)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
import numpy as np
arr=[[10, 20], [30, 40]]
arr1=np.array(arr)
print(arr1)
col=np.array([[50],
              [60]])
new=np.append(arr1,col,axis=1)
print(new)
new1=np.delete(new,0,axis=0)
print(new1)

[[10 20]
 [30 40]]
[[10 20 50]
 [30 40 60]]
[[30 40 60]]


In [ ]:
prices = np.array([[100, 200, 300],
                   [150, 250, 350]])
discounts=np.array([10,20,30])
brod=prices-discounts
print(brod)

[[ 90 180 270]
 [140 230 320]]


In [ ]:
packages = np.array([101, 102, 103, 104, 105, 106, 107, 108])
inventory_grid=np.reshape(2,4)

NameError: name 'np' is not defined

In [ ]:
import numpy as np
map=np.array([[[10,20,30],[40,50,60],[70,80,90]]],dtype=np.float32)
print(map)

[[[10. 20. 30.]
  [40. 50. 60.]
  [70. 80. 90.]]]


In [ ]:
booster_temps=np.array([[112.5,115.0,118.2,114.8],[120.4,122.1,125.6,121.0],[130.2,132.8,135.4,131.7]])
print(booster_temps)
print(f"Telemetry Grid Layout (Rows, Columns):{booster_temps.shape}")
print(f"Total Data Points Ingested:{booster_temps.size}")
print(f"Precision Metric Standard:{booster_temps.dtype}")

[[112.5 115.  118.2 114.8]
 [120.4 122.1 125.6 121. ]
 [130.2 132.8 135.4 131.7]]
Telemetry Grid Layout (Rows, Columns):(3, 4)
Total Data Points Ingested:12
Precision Metric Standard:float64


In [ ]:
ipl_stats=np.array([[[45,20],[28,12]],[[82,50],[64,42]],[[15,8],[33,15]]],dtype=np.int32)
print(f"CSK Analytics Tensor Structure:{ipl_stats.shape}")
print(f"Total Analytics Points Collected:{ipl_stats.size}")

CSK Analytics Tensor Structure:(3, 2, 2)
Total Analytics Points Collected:12


In [ ]:
import numpy as np
# Run this setup code in your notebook:
inventory = np.array([
    [45, 12, 88, 34],  # Row 0 (Beverages)
    [19, 72, 50, 61],  # Row 1 (Dairy)
    [91, 23, 64, 11],  # Row 2 (Snacks)
    [55, 80, 42, 99]   # Row 3 (Packaged Food)
])
print(inventory[1,:])
print(inventory[:,3])
print(inventory[2:,2:])

[19 72 50 61]
[34 61 11 99]
[[64 11]
 [42 99]]


In [ ]:
# Run this setup code in your notebook:
inventory = np.array([
    [45, 12, 88, 34],  # Row 0 (Beverages)
    [19, 72, 50, 61],  # Row 1 (Dairy)
    [91, 23, 64, 11],  # Row 2 (Snacks)
    [55, 80, 42, 99]   # Row 3 (Packaged Food)
])
inventory[2,1]=0
inventory[:,3]=0
inventory[0,0:2]=5
inventory[1,0:2]=5
print(inventory)

[[ 5  5 88  0]
 [ 5  5 50  0]
 [91  0 64  0]
 [55 80 42  0]]


In [ ]:
# Run this setup code in your notebook:
raw_bills = np.array([
    [150, 200, 350],  # Customer 1 bills
    [400, 120, 250],  # Customer 2 bills
    [500, 300, 100]   # Customer 3 bills
])
discount=raw_bills-50
print(discount)
container_fees = np.array([10, 15, 20])
total_cost=discount+container_fees
print(total_cost)

[[100 150 300]
 [350  70 200]
 [450 250  50]]
[[110 165 320]
 [360  85 220]
 [460 265  70]]


In [ ]:
grand_total=np.sum(total_cost)
customer_tools=np.sum(total_cost,axis=1)

In [ ]:
# Run this setup code in your notebook:
deliveries = np.array([
    [12, 15, 18, 14],  # Rider 0 deliveries over 4 days
    [10, 8,  11, 12],  # Rider 1 deliveries over 4 days
    [20, 22, 25, 19]   # Rider 2 deliveries over 4 days
])
print(np.max(deliveries))
print(np.sum(deliveries,axis=1))
print(np.mean(deliveries,axis=0))

25
[59 41 86]
[14. 15. 18. 15.]


In [ ]:
##AI Neural Network Layer Initialization
biases=np.ones([3,5])
print(biases)
pixel_indices=np.arange(10,51,5)
print(pixel_indices)
random_features=np.random.rand(3,3)
print(random_features)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[10 15 20 25 30 35 40 45 50]
[[0.69267812 0.95463009 0.25740931]
 [0.93709565 0.13699498 0.93135278]
 [0.64569736 0.353807   0.35421222]]


In [ ]:
import numpy as np
# Run this setup code in your notebook:
flat_pixels = np.array([0, 255, 128, 64, 200, 50, 90, 15, 255, 0, 128, 45])
print(flat_pixels.shape)
print(flat_pixels.reshape(3,4))
print(flat_pixels.reshape(2,2,3))

(12,)
[[  0 255 128  64]
 [200  50  90  15]
 [255   0 128  45]]
[[[  0 255 128]
  [ 64 200  50]]

 [[ 90  15 255]
  [  0 128  45]]]


In [ ]:
###Blinkit Cold-Storage Temperature Alert
import numpy as np
# Run this setup code in your notebook:
rack_temps = np.array([
    [3.2, 4.1, 5.5, 3.9],
    [6.2, 2.8, 3.1, 4.0],
    [4.5, 5.8, 3.6, 6.0]
])
hot_mask=rack_temps>5.0
print(hot_mask)
tem=rack_temps[hot_mask]
print(tem)
rack_temps[hot_mask]=0.0
print(rack_temps)

[[False False  True False]
 [ True False False False]
 [False  True False  True]]
[5.5 6.2 5.8 6. ]
[[3.2 4.1 0.  3.9]
 [0.  2.8 3.1 4. ]
 [4.5 0.  3.6 0. ]]


In [ ]:
###Flipkart Customer Profile Merging
server_1_data = np.array([
    [24, 12],  # Customer 1
    [35, 48]   # Customer 2
])
server_2_data = np.array([
    [15, 1],  # Customer 1
    [80, 4]   # Customer 2
])
server_3_data = np.array([
    [19, 3],   # Customer 3
    [42, 24]   # Customer 4
])
comh=np.hstack((server_1_data,server_2_data))
print(comh)
comv=np.vstack((server_1_data,server_3_data))
print(comv)

[[24 12 15  1]
 [35 48 80  4]]
[[24 12]
 [35 48]
 [19  3]
 [42 24]]


In [ ]:
# Run this setup code in your notebook:
delivery_times = np.array([
    [45, 12, 30],  # Route 0 times across 3 batches
    [15, 60, 22],  # Route 1 times across 3 batches
    [10, 5,  18]   # Route 2 times across 3 batches
])
print(np.sort(delivery_times,axis=1))
print(np.sort(delivery_times,axis=0))

[[12 30 45]
 [15 22 60]
 [ 5 10 18]]
[[10  5 18]
 [15 12 22]
 [45 60 30]]


In [ ]:
quantities = np.array([
    [10, 5, 20],  # Store 1 items sold
    [15, 8, 30]   # Store 2 items sold
])
prices = np.array([
    [40],  # Price of Milk
    [30],  # Price of Bread
    [10]   # Price of Eggs
])
print(quantities @ prices)

[[ 750]
 [1140]]


In [ ]:
from sys import addaudithook
# Run this setup code in your notebook:
transactions = np.array([1200, 45000, 150, 85000, 2300, 95000, 400])
audit_copy=transactions.copy()
print(audit_copy)
audit_copy=(transactions>1000) & (transactions<50000)
print(transactions[audit_copy])
flagged_transactions=np.where(transactions>50000,-999,transactions)
print(flagged_transactions)

[ 1200 45000   150 85000  2300 95000   400]
[ 1200 45000  2300]
[ 1200 45000   150  -999  2300  -999   400]


In [ ]:
np.random.seed(42)
points=np.linspace(0, 5, 5)
print(points)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.T)
print(matrix.flatten())
data = np.array([10, 20, 30, 40, 1000])
print(np.median(data))
print(np.std(data))

[0.   1.25 2.5  3.75 5.  ]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
30.0
390.1281840626232


In [ ]:
###Computer Vision Image Processing Pipeline
import numpy as np
np.random.seed(42)
raw_sensor_stream = np.random.randint(0, 256, size=24)
print("Raw Stream:", raw_sensor_stream)
###Reshape to Grid:
image_grid=(raw_sensor_stream.reshape(4,6))
print(image_grid)
###Matrix Orientation Update (Transpose)
corrected_grid=image_grid.T
print(corrected_grid)
###Data Normalization (Vectorized Math):
normalized_grid=corrected_grid / 255.0
print(normalized_grid)
###Glare Detection & Cleaning (np.where):
cleaned_grid=np.where(normalized_grid > 0.8, 0.5, normalized_grid)
print(cleaned_grid)
###System Metrics (Aggregations)
print(np.median(cleaned_grid))
print(np.max(cleaned_grid))

Raw Stream: [102 179  92  14 106  71 188  20 102 121 210 214  74 202  87 116  99 103
 151 130 149  52   1  87]
[[102 179  92  14 106  71]
 [188  20 102 121 210 214]
 [ 74 202  87 116  99 103]
 [151 130 149  52   1  87]]
[[102 188  74 151]
 [179  20 202 130]
 [ 92 102  87 149]
 [ 14 121 116  52]
 [106 210  99   1]
 [ 71 214 103  87]]
[[0.4        0.7372549  0.29019608 0.59215686]
 [0.70196078 0.07843137 0.79215686 0.50980392]
 [0.36078431 0.4        0.34117647 0.58431373]
 [0.05490196 0.4745098  0.45490196 0.20392157]
 [0.41568627 0.82352941 0.38823529 0.00392157]
 [0.27843137 0.83921569 0.40392157 0.34117647]]
[[0.4        0.7372549  0.29019608 0.59215686]
 [0.70196078 0.07843137 0.79215686 0.50980392]
 [0.36078431 0.4        0.34117647 0.58431373]
 [0.05490196 0.4745098  0.45490196 0.20392157]
 [0.41568627 0.5        0.38823529 0.00392157]
 [0.27843137 0.5        0.40392157 0.34117647]]
0.4019607843137255
0.792156862745098
